spring:
  application:
    name: TF_Java_2026_IAC_Bend
  datasource:
    url: ${DB_CONNECTION_STRING}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
azure:
  storage:
    account-name: ${AZURE_STORAGE_ACCOUNT_NAME:tfjava2026storageaccount}
    connection-string: ${BLOB_CONNECTION_STRING}
server:
  port: 8080

